### ISSUE TITLE
Go back in the routing

### ISSUE THREAD

**Issue by nonameplum** [jjgp/Routing#45]
I'm working on the MVVM example where `Routing` is used to deal with navigation. What I found difficult to do is back navigation. I think that if routing gives possibility to navigate forward it will be expected to have navigation back feature.

**Comment by jwalapr** [comment]
Yea it's a thought I've struggled with. We'd have to ship our own navigation controller or something that has the back button overridden. We'd also have to keep track of the view hierarchy so that we know where to pop back too. Unless I'm over thinking it.

**Comment by nonameplum** [comment]
Yeah I started working on this yesterday and I found that I wouldn't be easy because of the UIKit navigation behaviours.

I thought about adding to an array opened routes that could be used to navigate back.

```swift
var routeHistory = [(GoBackHandler, UIViewController)]()

public extension Routing {
    public func map(pattern: String,
                    tags: [String] = ["Views"],
                    owner: RouteOwner? = nil,
                    source: ControllerSource,
                    style: PresentationStyle = .Show,
                    goBack: GoBackHandler? = nil,
                    setup: PresentationSetup? = nil) -> RouteUUID {
        let routeHandler: RouteHandler = { [unowned self] (route, parameters, data, completed) in
            guard let root = UIApplication.sharedApplication().keyWindow?.rootViewController else {
                completed()
                return
            }

            let strongSelf = self
            let vc = strongSelf.controller(from: source)
            (vc as? RoutingPresentationSetup)?.setup(route, parameters: parameters, data: data)
            setup?(vc, parameters, data)

            var presenter = root
            while let nextVC = presenter.nextViewController() {
                presenter = nextVC
            }

            strongSelf.showController(vc, from: presenter, with: style, completion: completed)

            if let goBack = goBack {
                routeHistory.append((goBack, vc))
            }
        }

        return self.map(pattern, tags: tags, owner: owner, queue: dispatch_get_main_queue(), handler: routeHandler)
    }

    public func goBack() {
        if let (goBack, vc) = routeHistory.last {
            goBack(vc)
            routeHistory.removeLast()
        }
    }
}
```

**Comment by jwalapr** [comment]
Ultimately the UIKit behavior is what kept me from moving forward. It's still worth thinking about this topic further.

**Comment by nonameplum** [comment]
Yeah, I also thought about storing opened routes, and when open occurs to the route that is in history then we could navigate back but this could not work on some edge cases. So probably so intended `goBack` behaviour will be needed.

**Comment by nonameplum** [comment]
@jwalapr I raised this topic and played a bit with code. Take a look the branch https://github.com/nonameplum/Routing/tree/Feature/go_back and I also putted MVVM-R (Routing) example to github https://github.com/nonameplum/MVVM-R

**Comment by jwalapr** [comment]
Great!, I am going to look through this in more detail. After quick review I do notice that if you push/pop the UserDetails VC several times. Then enter in information and save. The go back behavior is broken. If you press save again it will crash.

It seems that the motivating factor for the go back is to pass data back to the original view controller correct?

**Comment by jwalapr** [comment]
I learned something new with the inner func call(_routes:... I wish I knew that was possible. Kudos.

**Comment by nonameplum** [comment]
Yeah. Probably there are bugs because it was quick test :) But it gives some look how backward feature could work. I thing about also something that would accept `backwardHandler` in the way like `PresentationStyle` works.

```swift
enum BackwardStyle {
    case Automatic
    case Custom(BackwardHandler)
```
In automatic case `goBack` could try automatically go back depending on the `PresentationStyle` that was used.

**Comment by nonameplum** [comment]
I fixed bug with crash that you mentioned. https://github.com/nonameplum/Routing/commit/35b2d4221e4f0c3f5de2af2f9f9e8da97862eb38 .
By the way I discovered feature because when VC was deallocated by the system then we can remove it form the historical opened routes :) So even without overriding default back button from the navigation bar `goBack` works good :)
